site_name: AIA (Advanced Interrupt Architecture) for Litex
repo_name: disdi/AIA_litex
repo_url: https://github.com/disdi/AIA_litex
site_url: https://saketsinha.de/
copyright: sake sinha

nav:
    - Home: index.md
    - Getting Started: nav/getting-started.md
    - Components:
      - nav/components/footer.md
    - Styles:
      - nav/styles/colors.md
    - Development:
      - nav/development/development-guide.md

theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.png
  theme_style: light
  site_name_style: bold
  title_style: bold
  sidebar: true
  navigation_depth: 2
  highlightjs: true
    - yaml
    - python
  colors:
    text: black
    title: black
    primary: black
    background: white
  components:
    site_name: true
    title: false
    menu: true
    preview: true
    footer: true

extra_javascript:
 - assets/custom.js
